version: "3"
services:
    client-reactjs:
        container_name: client-Chat
        build: 
            dockerfile: Dockerfile
            context: ./client_reactjs
        volumes:
            - ./client_reactjs:/client
        ports:
            - 3000:3000
        depends_on: 
            - server-nodejs
        stdin_open: true

    server-nodejs:
        container_name: server-Chat-api
        build: 
            dockerfile: Dockerfile
            context: ./server_nodejs_expressjs
        volumes:
            - ./server_nodejs_expressjs:/usr/src/app
        ports:
            - 4000:4000
        links:
            - mongodb
      
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        volumes:
            - ./dataMongoDocker/db:/dataMongoDocker/db
        ports:
            - 27017:27017
        
       
