version: "3"
services:
    client-reactjs:
        container_name: client
        build: 
            dockerfile: Dockerfile
            context: ./client-reactjs
        volumes:
            - ./client-reactjs:/client
        ports:
            - 3000:3000
        depends_on: 
            - server-nodejs
        stdin_open: true

    server-nodejs:
        container_name: server-api
        build: 
            dockerfile: Dockerfile
            context: ./server-nodejs_expressjs
        volumes:
            - ./server-nodejs/expressjs:/usr/src/app
        ports:
            - 4000:4000
        links:
            - mongodb
      
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        volumes:
            - ./dataMongoDocker/db:/dataMongoDocker/db
        ports:
            - 27017:27017
        
       
